@startuml "Diagrama de Componentes"
skinparam componentStyle uml2
skinparam package {
  BackgroundColor White
  BorderColor #7A1631
}
skinparam component {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
  ArrowColor #7A1631
}

package "Bounded Contexts" {
  component [IAM_BC] as IAM
  component [BusinessBC] as Business
  component [PredictionBC] as Prediction
  component [NotificationBC] as Notification
  component [SubscriptionBC] as Subscription
  component [DataIngestionBC] as DataIngestion
  component [ReportingBC] as Reporting
  component [SharedBC] as Shared
}

DataIngestion --> Prediction 
Business --> Prediction 
Prediction --> Notification
Business --> Notification 
Business --> Subscription 
Prediction --> Reporting 
Business --> Reporting 

IAM ..> Shared 
Business ..> Shared 
Prediction ..> Shared
Notification ..> Shared 
Subscription ..> Shared
DataIngestion ..> Shared
Reporting ..> Shared 

@enduml
