@startuml "Clases: Identity Access Management Context (IAM)"
skinparam class {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
  ArrowColor #7A1631
}
package IAM_BC {
  package UserAggregate {
    
    class User << (E,#FF7700) AggregateRoot >> {
      - UserId id
      - UserName name
      - Email email
      - PasswordHash password
      - UserStatus status
      + activateAccount(): void
      + suspendAccount(): void
      + changePassword(newPassword: PasswordHash): void
      + assignRole(role: Role): void
      + isSuspended(): Boolean
    }
    
    class UserId <<ValueObject>> {
      - Long value
    }
    class UserName <<ValueObject>> {
      - String firstName
      - String lastName
      + getFullName(): String
    }
    
    class Email <<ValueObject>> {
      - String address
      + isValidDomain(): Boolean
    }
    class PasswordHash <<ValueObject>> {
      - String hashValue
    }
    class Session << (E,#FF7700) Entity >> {
      - SessionId id
      - String sessionToken
      - LocalDateTime expirationDate
      - Boolean isActive
      + invalidateSession(): void
      + isExpired(): Boolean
    }
    class SessionId <<ValueObject>> {
      - Long value
    }
    enum UserStatus <<enum>> {
      ACTIVE
      SUSPENDED
      PENDING_VERIFICATION
    }
  }
  package RoleAggregate {
    class Role << (E,#FF7700) AggregateRoot >> {
      - RoleId id
      - String name
      - String description
      + updateDescription(newDesc: String): void
    }
    class RoleId <<ValueObject>> {
      - Long value
    }
  }
}
User "1" *-- "0..*" Session
User "1" o-- "1..*" Role
User "1" *-- "1" UserId
User "1" *-- "1" UserName
User "1" *-- "1" Email
User "1" *-- "1" PasswordHash
Session "1" *-- "1" SessionId
Role "1" *-- "1" RoleId
User --> UserStatus
@enduml