@startuml "Capas - DataIngestionBC"
skinparam componentStyle uml2
skinparam package {
  BackgroundColor #F9F9F9
  BorderColor #7A1631
}


package "DataIngestionBC" {
  
  component [Domain Layer\n(DataIntegrationLog, DataProvider,\nSanitizedPayload Aggregates)] as Domain
  
  component [Application Layer\n(Data Fetching & Integration Services)] as Application

  component [Interfaces Layer\n(Ingestion Controllers / Schedulers)] as Interfaces

  component [Infrastructure Layer\n(External API Adapters, Repositories)] as Infra

  Interfaces ..> Application 
  Application ..> Domain 
  Application ..> Infra 
  Infra ..> Domain 
}

[Prediction BC] ..> Interfaces : "Solicita datos estructurados"
Infra ..> [APIs Externas (Weather, Economy, Traffic, Events)] : "Consume datos crudos (JSON)"
Infra ..> [PostgreSQL DB] : "Persiste logs y snapshots"

@enduml
